# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fe264a511996d05eb81d9f61e6f223c7c15c12d6b3e9a2c6e0091c6c8e085f53d5ec1a75e8363e87284fb0958ed59bc37e44d3c0eda5c0977327d38704bab52

test:
  secret_key_base: 8053768b973c1cfe0be70d5f398086d9ac54661c539b8b6a8fc911bedf172f3e5b642f756c9e7245d4944b2f7dfe170e3a6d1580ef5c7daba64eeaf00c94a225

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
